/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface SpiCandidatAdd {
    'home': RouterHistory;
  }
  interface SpiCandidatAddAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface SpiCandidatDetail {
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface SpiCandidatDetailAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiCandidatRechercheNom {
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface SpiCandidatRechercheNomAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiCandidatRechercheUniversite {
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface SpiCandidatRechercheUniversiteAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiCandidatRecherche {}
  interface SpiCandidatRechercheAttributes extends StencilHTMLAttributes {}

  interface SpiEnseignantAdd {
    'home': RouterHistory;
  }
  interface SpiEnseignantAddAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface SpiEnseignantDetail {
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface SpiEnseignantDetailAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiEnseignantRecherche {}
  interface SpiEnseignantRechercheAttributes extends StencilHTMLAttributes {}

  interface SpiFormationAdd {
    'home': RouterHistory;
  }
  interface SpiFormationAddAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface SpiFormationDetail {
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface SpiFormationDetailAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHomeCandidat {}
  interface SpiHomeCandidatAttributes extends StencilHTMLAttributes {}

  interface SpiHomeEnseignant {}
  interface SpiHomeEnseignantAttributes extends StencilHTMLAttributes {}

  interface SpiHomeFormation {}
  interface SpiHomeFormationAttributes extends StencilHTMLAttributes {}

  interface SpiHomePromotion {}
  interface SpiHomePromotionAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiPromotionAdd {
    'home': RouterHistory;
  }
  interface SpiPromotionAddAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface SpiPromotionDetail {
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface SpiPromotionDetailAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SpiCandidatAdd': Components.SpiCandidatAdd;
    'SpiCandidatDetail': Components.SpiCandidatDetail;
    'SpiCandidatRechercheNom': Components.SpiCandidatRechercheNom;
    'SpiCandidatRechercheUniversite': Components.SpiCandidatRechercheUniversite;
    'SpiCandidatRecherche': Components.SpiCandidatRecherche;
    'SpiEnseignantAdd': Components.SpiEnseignantAdd;
    'SpiEnseignantDetail': Components.SpiEnseignantDetail;
    'SpiEnseignantRecherche': Components.SpiEnseignantRecherche;
    'SpiFormationAdd': Components.SpiFormationAdd;
    'SpiFormationDetail': Components.SpiFormationDetail;
    'SpiHeader': Components.SpiHeader;
    'SpiHomeCandidat': Components.SpiHomeCandidat;
    'SpiHomeEnseignant': Components.SpiHomeEnseignant;
    'SpiHomeFormation': Components.SpiHomeFormation;
    'SpiHomePromotion': Components.SpiHomePromotion;
    'SpiHome': Components.SpiHome;
    'SpiPromotionAdd': Components.SpiPromotionAdd;
    'SpiPromotionDetail': Components.SpiPromotionDetail;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'spi-candidat-add': Components.SpiCandidatAddAttributes;
    'spi-candidat-detail': Components.SpiCandidatDetailAttributes;
    'spi-candidat-recherche-nom': Components.SpiCandidatRechercheNomAttributes;
    'spi-candidat-recherche-universite': Components.SpiCandidatRechercheUniversiteAttributes;
    'spi-candidat-recherche': Components.SpiCandidatRechercheAttributes;
    'spi-enseignant-add': Components.SpiEnseignantAddAttributes;
    'spi-enseignant-detail': Components.SpiEnseignantDetailAttributes;
    'spi-enseignant-recherche': Components.SpiEnseignantRechercheAttributes;
    'spi-formation-add': Components.SpiFormationAddAttributes;
    'spi-formation-detail': Components.SpiFormationDetailAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home-candidat': Components.SpiHomeCandidatAttributes;
    'spi-home-enseignant': Components.SpiHomeEnseignantAttributes;
    'spi-home-formation': Components.SpiHomeFormationAttributes;
    'spi-home-promotion': Components.SpiHomePromotionAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-promotion-add': Components.SpiPromotionAddAttributes;
    'spi-promotion-detail': Components.SpiPromotionDetailAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLSpiCandidatAddElement extends Components.SpiCandidatAdd, HTMLStencilElement {}
  var HTMLSpiCandidatAddElement: {
    prototype: HTMLSpiCandidatAddElement;
    new (): HTMLSpiCandidatAddElement;
  };

  interface HTMLSpiCandidatDetailElement extends Components.SpiCandidatDetail, HTMLStencilElement {}
  var HTMLSpiCandidatDetailElement: {
    prototype: HTMLSpiCandidatDetailElement;
    new (): HTMLSpiCandidatDetailElement;
  };

  interface HTMLSpiCandidatRechercheNomElement extends Components.SpiCandidatRechercheNom, HTMLStencilElement {}
  var HTMLSpiCandidatRechercheNomElement: {
    prototype: HTMLSpiCandidatRechercheNomElement;
    new (): HTMLSpiCandidatRechercheNomElement;
  };

  interface HTMLSpiCandidatRechercheUniversiteElement extends Components.SpiCandidatRechercheUniversite, HTMLStencilElement {}
  var HTMLSpiCandidatRechercheUniversiteElement: {
    prototype: HTMLSpiCandidatRechercheUniversiteElement;
    new (): HTMLSpiCandidatRechercheUniversiteElement;
  };

  interface HTMLSpiCandidatRechercheElement extends Components.SpiCandidatRecherche, HTMLStencilElement {}
  var HTMLSpiCandidatRechercheElement: {
    prototype: HTMLSpiCandidatRechercheElement;
    new (): HTMLSpiCandidatRechercheElement;
  };

  interface HTMLSpiEnseignantAddElement extends Components.SpiEnseignantAdd, HTMLStencilElement {}
  var HTMLSpiEnseignantAddElement: {
    prototype: HTMLSpiEnseignantAddElement;
    new (): HTMLSpiEnseignantAddElement;
  };

  interface HTMLSpiEnseignantDetailElement extends Components.SpiEnseignantDetail, HTMLStencilElement {}
  var HTMLSpiEnseignantDetailElement: {
    prototype: HTMLSpiEnseignantDetailElement;
    new (): HTMLSpiEnseignantDetailElement;
  };

  interface HTMLSpiEnseignantRechercheElement extends Components.SpiEnseignantRecherche, HTMLStencilElement {}
  var HTMLSpiEnseignantRechercheElement: {
    prototype: HTMLSpiEnseignantRechercheElement;
    new (): HTMLSpiEnseignantRechercheElement;
  };

  interface HTMLSpiFormationAddElement extends Components.SpiFormationAdd, HTMLStencilElement {}
  var HTMLSpiFormationAddElement: {
    prototype: HTMLSpiFormationAddElement;
    new (): HTMLSpiFormationAddElement;
  };

  interface HTMLSpiFormationDetailElement extends Components.SpiFormationDetail, HTMLStencilElement {}
  var HTMLSpiFormationDetailElement: {
    prototype: HTMLSpiFormationDetailElement;
    new (): HTMLSpiFormationDetailElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeCandidatElement extends Components.SpiHomeCandidat, HTMLStencilElement {}
  var HTMLSpiHomeCandidatElement: {
    prototype: HTMLSpiHomeCandidatElement;
    new (): HTMLSpiHomeCandidatElement;
  };

  interface HTMLSpiHomeEnseignantElement extends Components.SpiHomeEnseignant, HTMLStencilElement {}
  var HTMLSpiHomeEnseignantElement: {
    prototype: HTMLSpiHomeEnseignantElement;
    new (): HTMLSpiHomeEnseignantElement;
  };

  interface HTMLSpiHomeFormationElement extends Components.SpiHomeFormation, HTMLStencilElement {}
  var HTMLSpiHomeFormationElement: {
    prototype: HTMLSpiHomeFormationElement;
    new (): HTMLSpiHomeFormationElement;
  };

  interface HTMLSpiHomePromotionElement extends Components.SpiHomePromotion, HTMLStencilElement {}
  var HTMLSpiHomePromotionElement: {
    prototype: HTMLSpiHomePromotionElement;
    new (): HTMLSpiHomePromotionElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiPromotionAddElement extends Components.SpiPromotionAdd, HTMLStencilElement {}
  var HTMLSpiPromotionAddElement: {
    prototype: HTMLSpiPromotionAddElement;
    new (): HTMLSpiPromotionAddElement;
  };

  interface HTMLSpiPromotionDetailElement extends Components.SpiPromotionDetail, HTMLStencilElement {}
  var HTMLSpiPromotionDetailElement: {
    prototype: HTMLSpiPromotionDetailElement;
    new (): HTMLSpiPromotionDetailElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'spi-candidat-add': HTMLSpiCandidatAddElement
    'spi-candidat-detail': HTMLSpiCandidatDetailElement
    'spi-candidat-recherche-nom': HTMLSpiCandidatRechercheNomElement
    'spi-candidat-recherche-universite': HTMLSpiCandidatRechercheUniversiteElement
    'spi-candidat-recherche': HTMLSpiCandidatRechercheElement
    'spi-enseignant-add': HTMLSpiEnseignantAddElement
    'spi-enseignant-detail': HTMLSpiEnseignantDetailElement
    'spi-enseignant-recherche': HTMLSpiEnseignantRechercheElement
    'spi-formation-add': HTMLSpiFormationAddElement
    'spi-formation-detail': HTMLSpiFormationDetailElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home-candidat': HTMLSpiHomeCandidatElement
    'spi-home-enseignant': HTMLSpiHomeEnseignantElement
    'spi-home-formation': HTMLSpiHomeFormationElement
    'spi-home-promotion': HTMLSpiHomePromotionElement
    'spi-home': HTMLSpiHomeElement
    'spi-promotion-add': HTMLSpiPromotionAddElement
    'spi-promotion-detail': HTMLSpiPromotionDetailElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'spi-candidat-add': HTMLSpiCandidatAddElement;
    'spi-candidat-detail': HTMLSpiCandidatDetailElement;
    'spi-candidat-recherche-nom': HTMLSpiCandidatRechercheNomElement;
    'spi-candidat-recherche-universite': HTMLSpiCandidatRechercheUniversiteElement;
    'spi-candidat-recherche': HTMLSpiCandidatRechercheElement;
    'spi-enseignant-add': HTMLSpiEnseignantAddElement;
    'spi-enseignant-detail': HTMLSpiEnseignantDetailElement;
    'spi-enseignant-recherche': HTMLSpiEnseignantRechercheElement;
    'spi-formation-add': HTMLSpiFormationAddElement;
    'spi-formation-detail': HTMLSpiFormationDetailElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home-candidat': HTMLSpiHomeCandidatElement;
    'spi-home-enseignant': HTMLSpiHomeEnseignantElement;
    'spi-home-formation': HTMLSpiHomeFormationElement;
    'spi-home-promotion': HTMLSpiHomePromotionElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-promotion-add': HTMLSpiPromotionAddElement;
    'spi-promotion-detail': HTMLSpiPromotionDetailElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
